spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/shipmonk-exchange-rates
spring.datasource.username=shipmonk
spring.datasource.password=secret
spring.datasource.fixer_api_key=ec4cadf1d3bcf4807427b6a5e570ed4d
