spring.datasource.url=jdbc:postgresql://${DB_HOST:127.0.0.1}:5432/shipmonk-exchange-rates
spring.datasource.username=shipmonk
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

fixer.api.base-url=http://data.fixer.io/api
fixer.api.key=${FIXER_API_KEY:ec4cadf1d3bcf4807427b6a5e570ed4d}

resilience4j.retry.instances.fixer.max-attempts=3
resilience4j.retry.instances.fixer.wait-duration=1s
resilience4j.retry.instances.fixer.enable-exponential-backoff=true
resilience4j.retry.instances.fixer.exponential-backoff-multiplier=2
resilience4j.retry.instances.fixer.retry-exceptions=com.shipmonk.testingday.rates.exception.TransientProviderException
